# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "D+QVqZIClzzsO907AiJ9TplrXud/NiVDeHl33rhXSvxZjWnav15fYiQT67Be1Wyazzv/6QS/RV45Epj3NN4bZixYPZcDqJ2mdHwhRJJHbw/7VorKrb3OgIswI+YSVXhT7JmV62BXsxg4sd30exaU5ZEcjhPro2/HFSX3XyCa7sCwKf3NW84lsKqS0T/YmvumSogTLfhB3jyCShmFv1fiTgTxZ3BYbPkzbGpAcqCQwBNJg0HXcG1IE5yXnDDGZQfmc+MZ+dFOOsME6xygZPBCiz8QN6WrilN1dt8GDzGRadUFkGrx4Y4kk0VKvxZWDHs1nTewtjfPdReqHtDyk2dcBGiCdvtSeCGXSjxm1vFPvE/uJtFBd3duHdX8G0uYgtOMmUw81c75e5GkKIGvTfVdylhbLw6ldluwkz9yLvEw8FkT1IKWOAjBuG0CGT4oJcfC2MPRKn+1pmTl8LFVhZ9DkHfUdmn95Js/47qyCt8yen8lB7dM0ngCK63KFHdRTbvIMVSMji5yyNc6boLNl6bEP3h3kTE/vA6eLmBzo4/GQKANzhloSp7jD0cOE1jgVcnHl4ig0WNVE+lIAGx3M3zGvouXBSDlOCxb1MQ4KQ1irhsy9t9ejkEe5TpFzajhSz1+tcLMl1b+K3ymTThvh0z7I4eHiQUIs3e6UwQcXKD5SO0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
