travis:
  secure:
    BINSTAR_TOKEN: D+QVqZIClzzsO907AiJ9TplrXud/NiVDeHl33rhXSvxZjWnav15fYiQT67Be1Wyazzv/6QS/RV45Epj3NN4bZixYPZcDqJ2mdHwhRJJHbw/7VorKrb3OgIswI+YSVXhT7JmV62BXsxg4sd30exaU5ZEcjhPro2/HFSX3XyCa7sCwKf3NW84lsKqS0T/YmvumSogTLfhB3jyCShmFv1fiTgTxZ3BYbPkzbGpAcqCQwBNJg0HXcG1IE5yXnDDGZQfmc+MZ+dFOOsME6xygZPBCiz8QN6WrilN1dt8GDzGRadUFkGrx4Y4kk0VKvxZWDHs1nTewtjfPdReqHtDyk2dcBGiCdvtSeCGXSjxm1vFPvE/uJtFBd3duHdX8G0uYgtOMmUw81c75e5GkKIGvTfVdylhbLw6ldluwkz9yLvEw8FkT1IKWOAjBuG0CGT4oJcfC2MPRKn+1pmTl8LFVhZ9DkHfUdmn95Js/47qyCt8yen8lB7dM0ngCK63KFHdRTbvIMVSMji5yyNc6boLNl6bEP3h3kTE/vA6eLmBzo4/GQKANzhloSp7jD0cOE1jgVcnHl4ig0WNVE+lIAGx3M3zGvouXBSDlOCxb1MQ4KQ1irhsy9t9ejkEe5TpFzajhSz1+tcLMl1b+K3ymTThvh0z7I4eHiQUIs3e6UwQcXKD5SO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
