travis:
  secure:
    BINSTAR_TOKEN: PHWf99DVB9AqfZPeEMVU/y9xgihxdkxuR6pYqgRBeFAQbVRqxYpaVHKgivU+64wnu2YJtpmTBxNL60kLMw20rjfTfdO4JKSKN0t/OuBG5R+TeiQe0lo4FwGuVhs1ujfdAQ/xANUnXUo83SlOQvKPAxyM7ttrtm7LlmogwuYTqE6szgtsBGgUy90q6/T8eoNe5rsvDk2kahjckEGqP5i2g5GfI7K74ly4SAd5N0cSurkNmK5dAxyzxlL0UHZltLfGbSG3CybiuZHlXdNQahydVzDtClH0bkbRgp//hVMfLAcOcCD4OQj7XSbximtkZygtjs25Myp4DCRAN5CdTRFC/Re7PRLH60AKuF89dREvWB/JUSCsU5JvNggifivMvz/QbfMZG6XZeI0H7ejqT9qyICdCex+Ir77eBrGbbqMkZ7aQqNTE7P/OnKGJHskDaBLBD+KcqFiGK1Umkeh/L1FhicFpSpw2TgAuadk5bnmH/ITe5YYpozzz5JXN0bm809bLROD9ysFowL8wheUInx3muF9ZME1D5/qjJVA693wGqF5ZN/DBHDEOD0ZWHMdvyZk/TtJsR3zjcdUUCRTU6Ip641WUCwj97c916u2lRNohPTiNyR1Q9J8D3I+NjS7If2cg0Rpb7D7veR5oSP8UYZ4K9qmBZY72+RrDD6KhBNE+qQM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
